### ISSUE TITLE
any way to make [tab] work on iPad with external keyboard?

### ISSUE THREAD

**Issue by briankelly** [syndicatefx/textpad#1]
I haven't found a combination that works, yet.

**Comment by syndicatefx** [comment]
Hi!
Tab key will not work, iPad or otherwise any keyboard. TextPad uses a `<textarea>` to capture text and the tab key by default is used by browsers to move to the next focusable form element or anchor on the page.

The only work around would be to maybe use a `<div contenteditable="true">` instead of a `<textarea>`, or add some Javascript to hack the tab key and opt-out of default usability. That is not an option at the moment, sorry.
