### ISSUE TITLE
Is it easy to support mutlitab?

### ISSUE THREAD

**Issue by uuvccc** [syndicatefx/textpad#4]

**Comment by syndicatefx** [comment]
Hi,
I am assuming you mean multiple browser tabs running textpad?
**No**, using localStorage the stored data is saved across browser sessions. Which obviously includes the same website open on multiple tabs.
A workaround for this, if you need multiple textpad instances with different key/values stored running, you could use something like Firefox Multi-Account Containers, which will work by opening textpad on different containers.

Otherwise, if what you mean is multiple notes(key/value) in the same app, that is not a feature that will be supported on this project.

**Comment by uuvccc** [comment]
> Hi,
> I am assuming you mean multiple browser tabs running textpad?
> **No**, using localStorage the stored data is saved across browser sessions. Which obviously includes the same website open on multiple tabs.
> A workaround for this, if you need multiple textpad instances with different key/values stored running, you could use something like Firefox Multi-Account Containers, which will work by opening textpad on different containers.
> 
> Otherwise, if what you mean is multiple notes(key/value) in the same app, that is not a feature that will be supported on this project.

Hi, syndicatefx. I see. Thank you very much for the reply! I will research some code to try to support this feature if I have time.
